version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
  azalea:
    image: epelesis/azalea:latest
    environment:
      - PORT=8000
    depends_on:
      - redis
    deploy:
      mode: replicated
      replicas: 3
